Skip Hg tests if Hg is not installed
I don't have Hg (the Mercurial VCS) installed. This means test_request_id fails
on my machine:

    $ ./runtests.py tests/integration/test_request_id.py
    Eden not available because: No module named configparser
    FAIL test_request_id.TestRequestIdCliJson.test_scmHgRequestId (0.008s)
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
	testMethod()
      File "/Users/mg/Projects/watchman/tests/integration/test_request_id.py", line 54, in test_scmHgRequestId
	self.skipIfNoHgRequestIdSupport()
      File "/Users/mg/Projects/watchman/tests/integration/test_request_id.py", line 41, in skipIfNoHgRequestIdSupport
	subprocess.call(["hg", "init"], env=env, cwd=root)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
	return Popen(*popenargs, **kwargs).wait()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
	errread, errwrite)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
	raise child_exception
    OSError: [Errno 2] No such file or directory
    [snip]
    PASS test_request_id.TestRequestIdLocalBser2.test_queryRequestId (0.014s)
    Ran 8, failed 4, skipped 0, concurrency 1

Hg is not required for Watchman to work, so Watchman's test suite should not
require Hg. Make test_request_id skip the Hg-requiring tests if Hg is not
installed:

    $ ./runtests.py tests/integration/test_request_id.py
    Eden not available because: No module named configparser
    PASS test_request_id.TestRequestIdLocalBser2.test_queryRequestId (0.013s)
    PASS test_request_id.TestRequestIdCliJson.test_queryRequestId (0.035s)
    SKIP test_request_id.TestRequestIdLocalJson.test_scmHgRequestId (0.000s) Hg not installed
    SKIP test_request_id.TestRequestIdLocalBser2.test_scmHgRequestId (0.000s) Hg not installed
    SKIP test_request_id.TestRequestIdLocalBser.test_scmHgRequestId (0.000s) Hg not installed
    SKIP test_request_id.TestRequestIdCliJson.test_scmHgRequestId (0.000s) Hg not installed
    PASS test_request_id.TestRequestIdLocalJson.test_queryRequestId (0.011s)
    PASS test_request_id.TestRequestIdLocalBser.test_queryRequestId (0.010s)
    Ran 8, failed 0, skipped 4, concurrency 1

Of course, do not change the behaviour of test_request_id if Hg *is* installed:

    $ ./runtests.py tests/integration/test_request_id.py
    Eden not available because: No module named configparser
    PASS test_request_id.TestRequestIdLocalBser.test_queryRequestId (0.012s)
    SKIP test_request_id.TestRequestIdLocalBser2.test_scmHgRequestId (0.281s) HGREQUESTID is not supported
    PASS test_request_id.TestRequestIdLocalJson.test_queryRequestId (0.013s)
    SKIP test_request_id.TestRequestIdLocalJson.test_scmHgRequestId (0.287s) HGREQUESTID is not supported
    SKIP test_request_id.TestRequestIdCliJson.test_scmHgRequestId (0.280s) HGREQUESTID is not supported
    PASS test_request_id.TestRequestIdLocalBser2.test_queryRequestId (0.010s)
    SKIP test_request_id.TestRequestIdLocalBser.test_scmHgRequestId (0.292s) HGREQUESTID is not supported
    PASS test_request_id.TestRequestIdCliJson.test_queryRequestId (0.040s)
    Ran 8, failed 0, skipped 4, concurrency 1